spring.application.name=DeskS
spring.datasource.url=jdbc:postgresql://localhost:5432/servicedesk
spring.datasource.username=postgres
spring.datasource.password=Fhassan1@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=kP3t6WxZ9qFg8rM1nY5jQ2hB0uV7cLsX4wA8zO6dT5bR1eN3yI9uP0kH7gL2xV5